name: CD_DEPLOY
on:
  push:
    branches:
      - main

jobs:
  setup-gcp:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
          terraform_wrapper: false

      - name: TF apply_prod
        working-directory: './'
        run: make apply_prod
        env:
          GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

  deploy-prefect:
    runs-on: ubuntu-latest
    container: prefecthq/prefect:latest
    env: 
      KEY: ${{ secrets.PREFECT_TENANT_API_KEY}}
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect auth login -k $KEY -w "bajajnakulgmailcom/data-engineering"
    - name: Register flow
      run: make deploy_prefect_flows
