name: CD_DEPLOY
on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: 'us-east-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
          terraform_wrapper: false

      - name: TF apply_prod
        working-directory: './'
        run: make apply_prod

  deploy-prefect:
    name: Deploy Prefect
    needs:  deploy-infra
    runs-on: ubuntu-latest
    container: prefecthq/prefect:2.7.7-python3.9
    env: 
      KEY: ${{ secrets.PREFECT_TENANT_API_KEY}}
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        requirements: prefect-requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect cloud login -k $KEY -w "bajajnakulgmailcom/data-engineering"
    - name: Register flow
      run: make deploy_prefect_flows
