name: CD_DEPLOY
on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: 'us-east-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
      
    - name: TF plan-prod
      working-directory: './'
      run: make plan_prod

  deploy-infra:
    runs-on: ubuntu-latest
    needs: tf-plan
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
          terraform_wrapper: false

      - name: TF apply_prod
        working-directory: './'
        run: make apply_prod
  
  changes:
    runs-on: ubuntu-latest
    needs: deploy-infra
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'etl/**'

  build-and-push-cloud-run-image:
    name: Build covid cloud run image
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: asia.gcr.io
          project_id: dataengineeringzoomcamp-2023
          image_name: prefect
          image_tag: covid, ${{ github.sha }}
          dockerfile: ./etl/Dockerfile
          context: .

  deploy-prefect:
    name: Deploy Prefect
    needs:  build-and-push-cloud-run-image
    runs-on: ubuntu-latest
    container: prefecthq/prefect:2.7.7-python3.9
    env: 
      KEY: ${{ secrets.PREFECT_TENANT_API_KEY}}
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        requirements: prefect-requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect cloud login -k $KEY -w "bajajnakulgmailcom/data-engineering"
    - name: Register flow
      run: make deploy_prefect_flows
