name: CI_TESTS
on:
  pull_request:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: 'us-east-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

jobs: 
  tf-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
      
    - name: TF plan-prod
      working-directory: './'
      run: make plan_prod
